export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_ADD = 'LOGIN_ADD';

export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';
export const PROJECTS_ADD = 'PROJECTS_ADD';
export const PROJECTS_POST = 'PROJECTS_POST';
export const PROJECTS_POSTING = 'PROJECTS_POSTING';
export const PROJECTS_PUT = 'PROJECTS_PUT';
export const PROJECTS_PUTTING = 'PROJECTS_PUTTING';

export const USERS_ADD = 'USERS_ADD';
export const USERS_LOGGING_IN = 'USERS_LOGGING_IN';
export const USERS_LOGINOUT = 'USERS_LOGINOUT';
export const USERS_GIVINGACCESS = 'USERS_GIVINGACCESS';
export const USERS_GIVEACCESS = 'USERS_GIVEACCESS';
export const USERS_ADDINGDELETINGTASK = 'USERS_ADDINGDELETINGTASK';
export const USERS_ADDDELETETASK = 'USERS_ADDDELETETASK';

export const FINANCES_LOADING = 'FINANCES_LOADING';
export const FINANCES_FAILED = 'FINANCES_FAILED';
export const BILLS_ADD = 'BILLS_ADD';
export const LOANS_ADD = 'LOANS_ADD';
export const FUNDS_ADD = 'FUNDS_ADD';
export const BILLS_POSTING = 'BILLS_POSTING';
export const BILLS_POST = 'BILLS_POST';
export const BILLS_PUTTING = 'BILLS_PUTTING';
export const BILLS_PUT = 'BILLS_PUT';
export const LOANS_POSTING = 'LOANS_POSTING';
export const LOANS_POST = 'LOANS_POST';
export const LOANS_PUTTING = 'LOANS_PUTTING';
export const LOANS_PUT = 'LOANS_PUT';
export const FUNDS_POSTING = 'FUNDS_POSTING';
export const FUNDS_POST = 'FUNDS_POST';
export const FUNDS_PUTTING = 'FUNDS_PUTTING';
export const FUNDS_PUT = 'FUNDS_PUT';

export const INVENTORY_LOADING = 'INVENTORY_LOADING';
export const INVENTORY_FAILED = 'INVENTORY_FAILED';
export const INVENTORY_ADD = 'INVENTORY_ADD';
export const INVENTORY_POSTING = 'INVENTORY_POSTING';
export const INVENTORY_POST = 'INVENTORY_POST';
export const INVENTORY_PUTTING = 'INVENTORY_PUTTING';
export const INVENTORY_PUT = 'INVENTORY_PUT';
export const STOCKS_ADD = 'STOCKS_ADD';
export const STOCKS_POSTING = 'STOCKS_POSTING';
export const STOCKS_POST = 'STOCKS_POST';
export const STOCKS_PUTTING = 'STOCKS_PUTTING';
export const STOCKS_PUT = 'STOCKS_PUT';

export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING';
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED';
export const EMPLOYEES_ADD = 'EMPLOYEES_ADD';
export const EMPLOYEES_POSTING = 'EMPLOYEES_POSTING';
export const EMPLOYEES_POST = 'EMPLOYEES_POST';
export const EMPLOYEES_PUTTING = 'EMPLOYEES_PUTTING';
export const EMPLOYEES_PUT = 'EMPLOYEES_PUT';
export const EMPLOYEES_ADDINGUNMARKING = 'EMPLOYEES_ADDINGUNMARKING';
export const EMPLOYEES_ADDLEAVE = 'EMPLOYEES_ADDLEAVE';
export const EMPLOYEES_UNMARK = 'EMPLOYEES_UNMARK';
export const EMPLOYEES_MARKING = 'EMPLOYEES_MARKING';
export const EMPLOYEES_MARK = 'EMPLOYEES_MARK';

export const COMPLAINTS_LOADING = 'COMPLAINTS_LOADING';
export const COMPLAINTS_FAILED = 'COMPLAINTS_FAILED';
export const COMPLAINTS_ADD = 'COMPLAINTS_ADD';
export const COMPLAINTS_POST = 'COMPLAINTS_POST';
export const COMPLAINTS_POSTINGDELETING = 'COMPLAINTS_POSTINGDELETING';
export const COMPLAINTS_POSTDELETE = 'COMPLAINTS_POSTDELETE';

export const SALES_LOADING = 'SALES_LOADING';
export const SALES_FAILED = 'SALES_FAILED';
export const SALES_ADD = 'SALES_ADD';
export const SALES_POST = 'SALES_POST';
export const SALES_POSTINGDELETING = 'SALES_POSTINGDELETING';
export const SALES_POSTDELETE = 'SALES_POSTDELETE';